 export const DATA=[
    {id:34,
title:"layer cake",
price:200,
desc:"hgffd",
img:'/assets/images/products/cake4.jpg'},  
{id:2,
    title:"cap cake",
    price:25,
    desc:"chocola crem",
    
    img:"/assets/images/products/blog-img1.png" },  
    {id:3,
        title:"korean cake",
        price:70,
        desc:"",
        img:"/assets/images/products/p1.jpeg"},  
        {id:1,
            title:"honey cake",
            price:150,
            desc:" steamed rice cakes made with honey and filled with sweetened sesame seeds.",
            img:'/assets/images/products/cake5.png'}, 
            {id:5,
                title:"Gâteau au chocolat",
                price:500,
                desc:"farine, sucre, cacao en poudre, œufs, beurre, lait, levure chimique.",
                img:"/assets/images/products/cake3.jpeg"},
                {id:6,
                    title:"korean cake",
                    price:200,
                    desc:"crem cheese ,vanille",
                    img:"/assets/images/products/p2.jpeg"},
                    {id:7,
                        title:"glass chocolat ",
                        price:200,
                        desc:"farine, sucre, cacao en poudre, œufs, beurre, lait, levure chimique.",
                        img:'/assets/images/products/cake6.png'}, 
                        {id:8,
                            title:"korean cake",
                            price:55,
                            desc:"farine, sucre, œufs, beurre, lait, levure chimique, extrait de vanille.",
                            img:"/assets/images/products/cake2.png"},
                            {id:0,
                                title:"korean cake",
                                price:70,
                                desc:" farine, sucre, œufs, beurre, lait, levure chimique, extrait de vanille.",
                                img:"/assets/images/products/cake1.png"},  
                                {id:13,
                                    title:"korean cake",
                                    price:70,
                                    desc:" farine, sucre, œufs, beurre, lait, levure chimique, extrait de vanille.",
                                    img:"/assets/images/products/cake4.jpg"},  
                                    {id:40,
                                        title:"korean cake",
                                        price:70,
                                        desc:" farine, sucre, œufs, beurre, lait, levure chimique, extrait de vanille.",
                                        img:'/assets/images/products/p3.jpeg'},  
                                        {id:66,
                                            title:"korean cake",
                                            price:70,
                                            desc:" farine, sucre, œufs, beurre, lait, levure chimique, extrait de vanille.",
                                            img:'/assets/images/products/p9.jpeg'}, 
                                            {id:80,
                                                title:"korean cake",
                                                price:70,
                                                desc:"farine, sucre, œufs, beurre, jus de citron, zeste de citron, levure chimique.",
                                                img:'/assets/images/products/p5.jpeg'},
                                                {id:89,
                                                    title:"korean cake",
                                                    price:80,
                                                    desc:"farine, sucre, œufs, bananes écrasées, huile végétale, levure chimique.",
                                                    img:'/assets/images/products/p6.jpeg'},
                                                    {id:300,
                                                        title:"korean cake",
                                                        price:50,
                                                        desc:" biscuits écrasés, sucre, beurre, fromage frais, œufs, crème sure, extrait de vanille.",
                                                        img:'/assets/images/products/p7.jpeg'}, 
                                                        {id:900,
                                                            title:"korean cake",
                                                            price:70,
                                                            desc:" farine, sucre, œufs, beurre, lait, colorant alimentaire rouge, vinaigre blanc, bicarbonate de soude.",
                                                            img:'/assets/images/products/p8.jpeg'},]